### ISSUE TITLE
Link from DappConnect websites

### ISSUE THREAD

**Issue by D4nte** [TheBojda/waku-uber#1]
Hi!

Would you be happy for me to point to your repo and article from the js-waku doc and upcoming DappConnect docs website?
Not only this is a great example of what can be done with Waku but also one of the first done with Vue.js.

Awesome job, feel free to join our discord if you want a chat: https://discord.gg/YqXnbqED

Cheers.

**Comment by TheBojda** [comment]
Thank you. It would be an honor for me. :)

Waku is awesome. A missing part that makes libp2p pubsub usable.

(Btw, I've used js-waku 0.13.1, cause something is wrong with the latest published npm package. You can check it with your own examples. https://github.com/status-im/js-waku/issues/323 )
